### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by poblabs** [bellerb/SiteMap#1]
Is this script still working for you? 

When I run it, it returns only 1 URL into the sitemap which is the parent url. 

However, if I `print link_hold` around line 34, I can see the array of links. But then they're all removed.

**Comment by exportio** [comment]
> Is this script still working for you?
> 
> When I run it, it returns only 1 URL into the sitemap which is the parent url.
> 
> However, if I `print link_hold` around line 34, I can see the array of links. But then they're all removed.

Same issue.  Only the root is returned.

**Comment by poblabs** [comment]
Seems like a dead project
